services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "1992:3000"        
    env_file:
      - ./back/.env        
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      API_URL: "https://back-dev-dpwo.onrender.com/"
    depends_on:
      - back              
